---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: position-query
  namespace: mu-architecture-demo
  labels:
    app: position-query
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: position-query
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: position-query
        image: dineshpillai/imcs-positionqueryservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: requireHz
          value: "false"
        - name: SPRING_PROFILES_ACTIVE
          value: native
        - name: VERSION
          value: 'K8S_TIMESTAMP'
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: position-query
  namespace: mu-architecture-demo
  labels:
    app: position-query
spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 8090
    targetPort: 8090
    nodePort: 31090
  selector:
    app: position-query