apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-2
  namespace: mu-architecture-demo
spec:
  clusterIP: None
  selector:
    component: hadoop-datanode-2
  ports:
  - name: p1
    port: 50010
  - name: p2
    port: 50020
  - name: p3
    port: 50075
  - name: p4
    port: 50475
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode-1
  namespace: mu-architecture-demo
spec:
  clusterIP: None
  selector:
    component: hadoop-datanode-1
  ports:
  - name: p1
    port: 50010
  - name: p2
    port: 50020
  - name: p3
    port: 50075
  - name: p4
    port: 50475
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hadoop-datanode-1
  namespace: mu-architecture-demo
  labels:
    component: hadoop-datanode-1
spec:
    serviceName: hadoop-datanode-1
    replicas: 1
    template:
      metadata:
        labels:
          app: hadoop-datanode-1
      spec:
        containers:
        - name: hadoop-datanode-1
          image: dineshpillai/hadoop-datanode:2.7.7
          imagePullPolicy: Always
          volumeMounts:
          - name: config
            mountPath: "/opt/hadoop/etc/hadoop"
            readOnly: true
          ports:
          - containerPort: 50010
          - containerPort: 50020
          - containerPort: 50075
          - containerPort: 50475
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumes:
        - name: config
          configMap:
            name: hadoopconf
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hadoop-datanode-2
  namespace: mu-architecture-demo
  labels:
    component: hadoop-datanode-2
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: kube-node-7
  serviceName: hadoop-datanode-2
    replicas: 1
    template:
      metadata:
        labels:
          app: hadoop-datanode-2
      spec:
        containers:
        - name: hadoop-datanode-2
          image: dineshpillai/hadoop-datanode:2.7.7
          imagePullPolicy: Always
          volumeMounts:
          - name: config
            mountPath: "/opt/hadoop/etc/hadoop"
            readOnly: true
          ports:
          - containerPort: 50010
          - containerPort: 50020
          - containerPort: 50075
          - containerPort: 50475
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumes:
        - name: config
          configMap:
            name: hadoopconf