kind: ConfigMap
apiVersion: v1
metadata:
  name: trade-injector
  labels:
    app: trade-injector
  namespace: mu-architecture-demo
data:
  application.yml: |-
    endpoints.trace.sensitive: false
    backend:
      ribbon:
        eureka.enabled: false
        client.enabled: true
        ServerListRefreshInterval: 15000