apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: mu-architecture-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: jobmanager
        image: flink:latest
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        volumeMounts:
        - name: flink-jobmanager-persistent-storage
          mountPath: /opt/flinkData
        - name: flink-conf-volume
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
      volumes:
      - name: flink-jobmanager-persistent-storage
        persistentVolumeClaim:
          claimName: flink-pv-claim
      - name: flink-conf-volume
        configMap:
          name: flink-conf-v1
