---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trade-imdg
  namespace: mu-architecture-demo
  labels:
    name: trade-imdg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: trade-imdg
    spec:
      hostAliases:
      - ip: "{{HOSTIPADDRESS}}"
        hostnames:
        - "{{HBASECONTAINERID}}"
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: dineshpillai/innovation-trade-imdg:latest
        name: trade-imdg
        imagePullPolicy: Always
        ports:
        - name: trade-imdg
          containerPort: 5701
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: trade-imdg-service
  namespace: mu-architecture-demo
  labels:
    app: trade-imdg
spec:
  ports:
    - port: 5701
  selector:
    app: trade-imdg

