---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: mu-architecture-demo
  labels:
    name: mongo
    app: mongo
spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - image: dineshpillai/mongo-db-repo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db-mongo
      volumes:
          - name: mongo-storage
            hostPath:
              path: /data/db-mongo

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mu-architecture-demo
  labels:
    name: mongo
    app: mongo
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-controller-1
  namespace: mu-architecture-demo
spec:
  replicas: 1
  selector:
    app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: zoo1
        image: dineshpillai/mu_zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1

---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: mu-architecture-demo
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-1
  type: NodePort

---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka
    component: kafka-broker
  name: kafka-broker
  namespace: mu-architecture-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-broker
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: kafka
        image:  dineshpillai/mu-kafka-v11
        ports:
        - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zoo1:2181
          - name: KAFKA_CREATE_TOPICS
            value: trade:16:1,market_data:16:1

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: mu-architecture-demo
  labels:
    app: kafka
    component: kafka-broker
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
    component: kafka-broker
