apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: mu-architecture-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: taskmanager
        image: flink:latest
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        volumeMounts:
        - name: flink-taskmanager-persistent-storage
          mountPath: /opt/flinkData
        - name: flink-conf-volume
          mountPath: /opt/flink/conf/flink-conf.yaml
          subPath: flink-conf.yaml
      volumes:
      - name: flink-taskmanager-persistent-storage
        persistentVolumeClaim:
          claimName: flink-pv-claim
      - name: flink-conf-volume
        configMap:
          name: flink-conf-v1
