apiVersion: v1
kind: Service
metadata:
  name: hbase-master-a
  namespace: mu-architecture-demo
spec:
  clusterIP: None
  selector:
    app: hbase-master-a
  ports:
  - name: p1
    port: 16000
  - name: p2
    port: 16010
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: hbase-master-b
#  namespace: mu-architecture-demo
#spec:
#  clusterIP: None
#  selector:
#    app: hbase-master-b
#  ports:
#  - name: p1
#    port: 16000
#  - name: p2
#    port: 16010
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hbase-master-a
  name: hbase-master-a
  namespace: mu-architecture-demo
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: HBASE_SERVER_TYPE
      value: master
    - name: HDFS_PATH
      value: mycluster
    - name: ZOOKEEPER_SERVICE_LIST
      value: zoo1
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: ZNODE_PARENT
      value: hbase
    image: dineshpillai/hbase-hdfs
    imagePullPolicy: Always
    name: hbase-master-a
    ports:
    - containerPort: 16000
      protocol: TCP
    - containerPort: 16010
      protocol: TCP
---
#apiVersion: v1
#kind: Pod
#metadata:
#  labels:
#    app: hbase-master-b
#  name: hbase-master-b
#  namespace: mu-architecture-demo
#spec:
#  containers:
#  - env:
#    - name: POD_NAMESPACE
#      valueFrom:
#        fieldRef:
#          fieldPath: metadata.namespace
#    - name: POD_NAME
#      valueFrom:
#        fieldRef:
#          fieldPath: metadata.name
#    - name: HBASE_SERVER_TYPE
#      value: master
#    - name: HDFS_PATH
#      value: mycluster
#    - name: ZOOKEEPER_SERVICE_LIST
#      value: zoo1
#    - name: ZOOKEEPER_PORT
#      value: "2181"
#    - name: ZNODE_PARENT
#      value: hbase
#    image: dineshpillai/hbase-hdfs
#    imagePullPolicy: Always
#    name: hbase-master-b
#    ports:
#    - containerPort: 16000
#      protocol: TCP
#    - containerPort: 16010
#      protocol: TCP