kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-client-service
  labels:
    app: hello-client-service
  namespace: hw
data:
  application.yml: |-
    endpoints.trace.sensitive: false
    backend:
      ribbon:
        eureka.enabled: false
        client.enabled: true
        ServerListRefreshInterval: 15000